- name: Set up servers
  hosts: ctf_servers
  tasks:
    - name: Run start.sh in services/A
      ansible.builtin.shell: |
        cd /home/ctf/services/A && bash -x start.sh
      args:
        chdir: /home/ctf
    - name: Run start.sh in services/B
      ansible.builtin.shell: |
        cd /home/ctf/services/B && bash -x start.sh
      args:
        chdir: /home/ctf
