- name: Stop services
  hosts: ctf_servers
  tasks:
    - name: Run stop.sh in services/ssh
      ansible.builtin.shell: |
        cd /home/ctf/services/ssh && ./stop.sh
      args:
        chdir: /home/ctf
    - name: Run stop.sh in services/web
      ansible.builtin.shell: |
        cd /home/ctf/services/web && ./stop.sh
      args:
        chdir: /home/ctf
    - name: Run stop.sh in services/app
      ansible.builtin.shell: |
        cd /home/ctf/services/app && ./stop.sh
      args:
        chdir: /home/ctf
